# Generated by Django 3.2.14 on 2024-06-03 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sizer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='upload_file_folder/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
