# Generated by Django 3.2.14 on 2024-06-04 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sizer', '0002_uploadedfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='excel_item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sizerID', models.CharField(max_length=100)),
                ('workload_name', models.CharField(max_length=100)),
                ('cluster_name', models.CharField(max_length=100)),
                ('vm_qty', models.IntegerField()),
                ('vCpu', models.IntegerField()),
                ('vcpu_pcore', models.IntegerField()),
                ('memory', models.IntegerField()),
                ('disk', models.IntegerField()),
            ],
        ),
    ]
