# Generated by Django 3.2.14 on 2024-06-11 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sizer', '0004_item'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
    ]
