# Generated by Django 3.2.14 on 2024-06-11 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sizer', '0005_delete_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='data_process',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
