# Generated by Django 3.2.14 on 2024-06-11 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sizer', '0006_auto_20240611_0110'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='create_user',
            field=models.CharField(default='admin', max_length=100),
        ),
    ]
