# Generated by Django 3.2.14 on 2024-06-11 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sizer', '0007_uploadedfile_create_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='excel_item',
            name='upload_file_id',
            field=models.IntegerField(default=3),
        ),
    ]
