# Generated by Django 3.2.14 on 2024-06-13 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sizer', '0008_excel_item_upload_file_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='sizer_id',
            field=models.CharField(default='', max_length=100),
        ),
    ]
