# Generated by Django 3.2.14 on 2024-06-13 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sizer', '0009_uploadedfile_sizer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='workstatus',
            field=models.CharField(default='', max_length=100),
        ),
    ]
