# Generated by Django 3.2.14 on 2024-06-14 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sizer', '0010_uploadedfile_workstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='progress',
            field=models.IntegerField(default=0),
        ),
    ]
