# Generated by Django 3.2.14 on 2024-06-14 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sizer', '0011_uploadedfile_progress'),
    ]

    operations = [
        migrations.CreateModel(
            name='task_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskuser', models.CharField(max_length=100)),
                ('sizerID', models.CharField(max_length=100)),
                ('workload_name', models.CharField(max_length=100)),
                ('cluster_name', models.CharField(max_length=100)),
                ('workstatus', models.CharField(default='', max_length=100)),
                ('progress', models.IntegerField(default=0)),
                ('taskdate_at', models.DateTimeField(auto_now_add=True)),
                ('upload_file_id', models.IntegerField(default=3)),
            ],
        ),
    ]
