# Generated by Django 3.2.14 on 2024-06-18 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sizer', '0012_task_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='excel_item',
            name='api_insert',
            field=models.CharField(default='', max_length=100),
        ),
    ]
